Wasm samples
afonsolage/bevy_ecss pull request #36
Opened 2023-11-19 17:14 UTC by Leinnan

As in title, we can have samples in docs: https://leinnan.github.io/bevy_ecss/example_simple.html

2023-11-19 20:01 UTC, afonsolage requested changes
Another nice idea, those example on docs will be great.

We should also include on example pages the `.css` file, so users can understand what's going on.

2023-11-19 21:40 UTC, Leinnan commented on book/src/SUMMARY.md
> +- [Hot reload](./example_editor.md)
True, updated

2023-11-19 21:42 UTC, Leinnan commented
Updated, also fixed alpha.css because it did have wrong selector.

2023-11-20 06:21 UTC, afonsolage approved these changes

2023-11-20 06:21 UTC, merged